//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int StmasId { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime CreDate { get; set; }
        public string SlipFileName { get; set; }
        public string TaxFileName { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Stmas Stmas { get; set; }
    }
}
