//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dlvprofile
    {
        public int id { get; set; }
        public int ProfileId { get; set; }
        public int DlvId { get; set; }
    
        public virtual Istab Istab { get; set; }
        public virtual Istab Istab1 { get; set; }
    }
}
