//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Istab()
        {
            this.Dlvprofile = new HashSet<Dlvprofile>();
            this.Dlvprofile1 = new HashSet<Dlvprofile>();
            this.Stcrd = new HashSet<Stcrd>();
            this.Stcrd1 = new HashSet<Stcrd>();
            this.Popr = new HashSet<Popr>();
            this.Popr1 = new HashSet<Popr>();
            this.Stmas = new HashSet<Stmas>();
            this.Stmas1 = new HashSet<Stmas>();
            this.Stmas2 = new HashSet<Stmas>();
            this.Stmas3 = new HashSet<Stmas>();
            this.Stmas4 = new HashSet<Stmas>();
            this.Oesoit = new HashSet<Oesoit>();
            this.Poprit = new HashSet<Poprit>();
            this.Stcrd2 = new HashSet<Stcrd>();
        }
    
        public int Id { get; set; }
        public string TabTyp { get; set; }
        public string TypCod { get; set; }
        public string AbbreviateTh { get; set; }
        public string AbbreviateEn { get; set; }
        public string TypDesTh { get; set; }
        public string TypDesEn { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public int CreBy { get; set; }
        public System.DateTime CreDate { get; set; }
        public Nullable<int> ChgBy { get; set; }
        public Nullable<System.DateTime> ChgDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dlvprofile> Dlvprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dlvprofile> Dlvprofile1 { get; set; }
        public virtual InternalUsers InternalUsers { get; set; }
        public virtual InternalUsers InternalUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stcrd> Stcrd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stcrd> Stcrd1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Popr> Popr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Popr> Popr1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stmas> Stmas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stmas> Stmas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stmas> Stmas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stmas> Stmas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stmas> Stmas4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oesoit> Oesoit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poprit> Poprit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stcrd> Stcrd2 { get; set; }
    }
}
