//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg
    {
        public int Id { get; set; }
        public string MsgToken { get; set; }
        public int MsgType { get; set; }
        public string MsgContent { get; set; }
        public string MsgLink { get; set; }
        public string MsgFrom { get; set; }
        public string MsgTo { get; set; }
        public int Status { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
