//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oesoit
    {
        public int Id { get; set; }
        public int OesoId { get; set; }
        public Nullable<int> PopritId { get; set; }
        public int StmasId { get; set; }
        public string StkDes { get; set; }
        public Nullable<System.DateTime> DlvDat { get; set; }
        public decimal OrdQty { get; set; }
        public int TquCod { get; set; }
        public decimal UnitPrice { get; set; }
        public string Disc { get; set; }
        public decimal DiscAmt { get; set; }
        public decimal TrnVal { get; set; }
        public string VatCode { get; set; }
    
        public virtual Istab Istab { get; set; }
        public virtual Oeso Oeso { get; set; }
        public virtual Poprit Poprit { get; set; }
        public virtual Stmas Stmas { get; set; }
    }
}
