//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poprit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poprit()
        {
            this.Oesoit = new HashSet<Oesoit>();
        }
    
        public int Id { get; set; }
        public int PoprId { get; set; }
        public int StmasId { get; set; }
        public string StkDes { get; set; }
        public Nullable<System.DateTime> RcvDat { get; set; }
        public decimal OrdQty { get; set; }
        public int TquCod { get; set; }
        public decimal UnitPrice { get; set; }
        public string Disc { get; set; }
        public decimal DiscAmt { get; set; }
        public decimal TrnVal { get; set; }
        public string VatCod { get; set; }
        public string SoNum { get; set; }
        public Nullable<System.DateTime> SoDat { get; set; }
        public Nullable<int> SoBy { get; set; }
        public Nullable<System.DateTime> SoCreDate { get; set; }
        public string SoRemark { get; set; }
        public string IvNum { get; set; }
        public Nullable<System.DateTime> IvDat { get; set; }
        public Nullable<int> IvBy { get; set; }
        public Nullable<System.DateTime> IvCreDate { get; set; }
        public string EmsTracking { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public string IvRemark { get; set; }
    
        public virtual InternalUsers InternalUsers { get; set; }
        public virtual InternalUsers InternalUsers1 { get; set; }
        public virtual Istab Istab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oesoit> Oesoit { get; set; }
        public virtual Popr Popr { get; set; }
        public virtual Stmas Stmas { get; set; }
    }
}
