//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stcrd
    {
        public int Id { get; set; }
        public Nullable<int> StmasId { get; set; }
        public Nullable<int> ArtrnId { get; set; }
        public string StkDes { get; set; }
        public Nullable<int> Department { get; set; }
        public string Posopr { get; set; }
        public Nullable<int> LocCod { get; set; }
        public string Docnum { get; set; }
        public System.DateTime DocDat { get; set; }
        public string RefNum { get; set; }
        public string Free { get; set; }
        public string VatCod { get; set; }
        public decimal TrnQty { get; set; }
        public int TquCod { get; set; }
        public decimal TFactor { get; set; }
        public decimal UnitPr { get; set; }
        public string Disc { get; set; }
        public decimal DiscAmt { get; set; }
        public decimal TrnVal { get; set; }
        public bool RetStk { get; set; }
        public decimal XTrnQty { get; set; }
        public decimal XUnitPr { get; set; }
        public decimal XTrnVal { get; set; }
        public decimal XSalVal { get; set; }
        public decimal NetVal { get; set; }
        public string VatCode { get; set; }
    
        public virtual Artrn Artrn { get; set; }
        public virtual Istab Istab { get; set; }
        public virtual Istab Istab1 { get; set; }
        public virtual Istab Istab2 { get; set; }
        public virtual Stmas Stmas { get; set; }
    }
}
