//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stmas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stmas()
        {
            this.Cart = new HashSet<Cart>();
            this.Oesoit = new HashSet<Oesoit>();
            this.Poprit = new HashSet<Poprit>();
            this.Stcrd = new HashSet<Stcrd>();
        }
    
        public int Id { get; set; }
        public string Stkcod { get; set; }
        public string StkDesTh { get; set; }
        public string StkDesEn { get; set; }
        public string Barcod { get; set; }
        public string ProductImg { get; set; }
        public string StkTyp { get; set; }
        public int StkGrp { get; set; }
        public Nullable<int> Acccod { get; set; }
        public int Qucod { get; set; }
        public Nullable<int> Cqucod { get; set; }
        public Nullable<int> Squcod { get; set; }
        public Nullable<int> Pqucod { get; set; }
        public Nullable<decimal> Cfactor { get; set; }
        public Nullable<decimal> Sfactor { get; set; }
        public Nullable<decimal> Pfactor { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Stkcods { get; set; }
        public string NegAllow { get; set; }
        public Nullable<decimal> Sellpr1 { get; set; }
        public Nullable<decimal> Sellpr2 { get; set; }
        public Nullable<decimal> Sellpr3 { get; set; }
        public Nullable<decimal> Sellpr4 { get; set; }
        public Nullable<decimal> Sellpr5 { get; set; }
        public string Vatcod { get; set; }
        public Nullable<decimal> Stnpr { get; set; }
        public Nullable<decimal> Totbal { get; set; }
        public Nullable<bool> ReserveBool { get; set; }
        public Nullable<int> ReserveInt { get; set; }
        public Nullable<decimal> ReserveDec { get; set; }
        public string ReserveStr { get; set; }
        public Nullable<decimal> ComRate { get; set; }
        public string CreBy { get; set; }
        public System.DateTime CreDate { get; set; }
        public string ChgBy { get; set; }
        public Nullable<System.DateTime> ChgDate { get; set; }
        public string Status { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual Istab Istab { get; set; }
        public virtual Istab Istab1 { get; set; }
        public virtual Istab Istab2 { get; set; }
        public virtual Istab Istab3 { get; set; }
        public virtual Istab Istab4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oesoit> Oesoit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poprit> Poprit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stcrd> Stcrd { get; set; }
    }
}
